mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: on
  type-handlers-package: com.ranranx.aolie.core.ds.dataoperator.mybatis
logging:
  pattern:
    console: "%C:%L %m%n"
#pagehelper.
pagehelper:
  autoDialect: true
  closeConn: true
  hello: \u4F60\u597D
  nihao: Hello
  offset-as-page-num: false
aolie:
  uploadpath: "g:/affix_location"